sonar:
 url: https://host.sonar/api
 token: token

https.proxy:
 host: host
 port: 123
 user: user
 password: xxxx


#disable the embedded web server in Spring Boot
spring:
 main:
  web-application-type: none

teams:
 sprint: 42
 teamA:
  projetA:
   key: k1
   branch: master
  projetBg:
   key: log
 teamB:
  projetB:
   key: keB
   branch: develop
